spring:
  mvc:
    #swagger运行报错时候添加
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: 123456

  redis:
    host: 127.0.0.1
    port: 6379
    #password: 123456
    database: 3 #操作的是0号数据库
    jedis:
      #Redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接

mybatis:
  #别名
  type-aliases-package: cn.bdqn.model
  #映射
  mapper-locations: calsspath:cn/bdqn/dao/*.xml